---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:17.0.0
  amd64: ghcr.io/hassio-addons/base-python/amd64:17.0.0
  armhf: ghcr.io/hassio-addons/base-python/armhf:17.0.0
  armv7: ghcr.io/hassio-addons/base-python/armv7:17.0.0
  i386: ghcr.io/hassio-addons/base-python/i386:17.0.0
args:
  BLUETTI_MQTT_VERSION: "cd5b38485b773c000b7995a9a6da1436ac198e86"
labels:
  org.opencontainers.image.title: "Bluetti to MQTT"
  org.opencontainers.image.description: "MQTT bridge between Bluetti and Home Assistant"
  org.opencontainers.image.source: "https://github.com/LzbnAndr313/bluetti2mqtt"
  org.opencontainers.image.licenses: "MIT"